### ISSUE TITLE
Animation problems

### ISSUE THREAD

**Issue by Mikhus** [Mikhus/canvas-gauges#106]
1. Overlapping animations which is called more often than initial animation duration causes CPU resource utilization even if real value is not changed.
2. Wrong needle positioning (south oriented) on some animations caused by wrong animation progress calculation in some cases (NaN values produced)

**Comment by Mikhus** [comment]
Fixed in branch v2.1.3

**Comment by mainstreetmark** [comment]
I'm still seeing the NaN in canvas-gauges@2.1.4.

Will try to reproduce, but it's quite intermittent.

**Comment by marcossapp** [comment]
For me it shows always. It´s a pity for a such great plugin. I also removed animation and NaN still appears.
